config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :sessions, only:[:new, :create, :destroy]
  get 'login' => 'sessions#new', as: 'login'
  get 'logout' => 'sessions#destroy', as: 'logout'
  get 'sign_up' => 'users#new', as: 'sign_up'

  resources :passwords, only:[:new, :create]

  root 'users#index'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_one :profile, dependent: :destroy
  accepts_nested_attributes_for :profile

  validates :username, :email, presence: true
  validates :email, uniqueness: true, format:{with:/\A[^@\s]+@([-\w]+\.)+[a-z]{2,}\Z/}
  validates :password, presence:true, length:{minimum: 6},  on: :create

  before_create :generate_token

  def refresh_token!
    generate_token
    save!(validate:false)
  end
  def generate_token
    begin
      self.token = SecureRandom.hex
    end while User.exists?(token:token)
  end

  def change_password(new_password)
    update!(password:new_password, password_confirmation:new_password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= session[:token].try{|token| User.find_by(token:token)}
  end
  helper_method :current_user
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  def new
    @form = PasswordForm.new(current_user)
  end
  def create
    @form = PasswordForm.new(current_user)
    if @form.submit(form_params)
      redirect_to root_url, notice:'Password changed successfully.'
    else
      render 'new'
    end
  end

  private
  def form_params
    params.require(:password_form).permit(:original_password, :new_password, :new_password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      user.refresh_token!
      session[:token] = user.token
      redirect_to root_url, notice:'Log in successfully.'
    else
      flash.now[:error] = 'Invalid email or password.'
      render 'new'
    end
  end

  def destroy
    session[:token] = nil
    redirect_to root_url, notice:'Log out successfully.'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  def new
    @user = User.new
    @user.build_profile
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user)
        .permit(:email, :password, :password_confirmation, :username,
          profile_attributes:[:twitter_name, :github_name, :bio])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    %title my_form_objects_416

    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{:type => "button", :data => {:toggle => "collapse", :target => "#navbar"}, :aria => {:expanded => "false", :controls => "navbar"} }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Project name", "#", :class => "navbar-brand"
        #navbar.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li.active
              %a{:href => "#"} Home
            %li
              %a{:href => "#about"} About
            %li
              %a{:href => "#contact"} Contact
          %ul.nav.navbar-nav.navbar-right
            - if current_user
              %li= link_to "Profile #{current_user.username}", current_user
              %li= link_to "Change password", new_password_path
              %li= link_to 'Logout', logout_path
            - else
              %li= link_to 'Sin Up', sign_up_path
              %li= link_to 'Log In', login_path
    .container
      - flash.each do |name, msg|
        = content_tag :div, :class => "alert alert-#{%w[alert error].include?(name.to_s) ? "danger" : "success" } alert-dismissable", :role => "alert" do
          %button.close{:type => "button", :data => {:dismiss => "alert"} }
            %span{:aria => {:hidden => "true"} } &times;
            %span.sr-only Close
          = msg
      = yield

app/views/users/_form.html.haml
= simple_form_for(@user) do |f|
  = f.error_notification

  .form-inputs
    = f.input :email
    = f.input :username
    = f.input :password
    = f.input :password_confirmation
    -#= f.input :subscribed_at
    = f.simple_fields_for :profile, @user.profile do |builder|
      = render 'profile_form', f:builder

  .form-actions
    = f.button :submit

app/views/users/_profile_form.html.haml
%h3 Profile
= f.input :twitter_name
= f.input :github_name
= f.input :bio

app/views/users/edit.html.haml
.page-header
  = link_to users_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @user, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing user

= render 'form'

app/views/users/index.html.haml
.page-header
  = link_to new_user_path, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New User
  %h1 Listing users

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Email
        %th Password digest
        %th Token
        %th Username
        %th Subscribed at
        %th
        %th
        %th

    %tbody
      - @users.each do |user|
        %tr
          %td= user.email
          %td= user.password_digest
          %td= user.token
          %td= user.username
          %td= user.subscribed_at
          %td= link_to 'Show', user
          %td= link_to 'Edit', edit_user_path(user)
          %td= link_to 'Destroy', user, :data => { confirm: 'Are you sure?' }, :method => :delete

app/views/users/new.html.haml
.page-header
  = link_to users_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New user

= render 'form'

app/views/users/show.html.haml
.page-header
  = link_to users_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_user_path(@user), :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show user

%dl.dl-horizontal
  %dt Email:
  %dd= @user.email
  %dt Password digest:
  %dd= @user.password_digest
  %dt Token:
  %dd= @user.token
  %dt Username:
  %dd= @user.username
  %dt Subscribed at:
  %dd= @user.subscribed_at

%h4 Profile
- @user.profile.try do |p|
  %dl.dl-horizontal
    %dt Twitter:
    %dd= p.twitter_name
    %dt Github:
    %dd= p.github_name
    %dt bio:
    %dd= p.bio